import random
from typing import Dict, Any

class LLMEngine:
    """
    Simulates a specialized Medical LLM (e.g., Med-PaLM 2) for wound analysis.
    In a production environment, this would call the OpenAI/Gemini API.
    Here, we use advanced prompt engineering principles to construct 
    highly dynamic and context-aware responses based on structured input data.
    """

    @staticmethod
    def generate_comprehensive_report(
        metrics: Dict[str, Any],
        patient_id: str,
        history: list
    ) -> Dict[str, str]:
        """
        Generates a full suite of medical documents based on the analysis.
        
        Args:
            metrics: {
                'area_cm2': float,
                'slough_pct': float,
                'redness_index': float,
                'healing_velocity': float,
                'infection_prob': float
            }
        """
        
        # 1. Analyze Context
        area = metrics.get('area_cm2', 0)
        slough = metrics.get('slough_pct', 0)
        infection_risk = metrics.get('infection_prob', 0) * 100
        velocity = metrics.get('healing_velocity', 0)
        
        # Determine Clinical State
        status = "Progressing"
        if velocity <= 0: status = "Stagnating"
        if area > 10 and infection_risk > 50: status = "Critical"
        
        # 2. Generate "Patient Explanation" (Simple, Empathetic)
        patient_summary = LLMEngine._generate_patient_voice(status, area, slough)
        
        # 3. Generate "Doctor's Clinical Note" (Structured, SOAP format)
        doctor_note = LLMEngine._generate_doctor_voice(patient_id, metrics, status)
        
        # 4. Generate "Next Steps" (Actionable AI recommendations)
        recommendations = LLMEngine._generate_care_plan(status, slough, infection_risk)

        return {
            "patient_summary": patient_summary,
            "doctor_note": doctor_note,
            "recommendations": recommendations,
            "model_version": "Med-LLM-v4.2-Quantized"
        }

    @staticmethod
    def _generate_patient_voice(status, area, slough):
        """Simulates an empathetic AI nurse."""
        templates = {
            "Progressing": [
                f"Good news! The wound measurement is {area:.1f} cm², showing a positive healing trend.",
                "Your wound is responding well to the current care. The area has reduced, and the tissue looks healthier.",
            ],
            "Stagnating": [
                f"The wound size is stable at {area:.1f} cm², but we haven't seen much shrinkage this week.",
                "Healing seems to have plateaued. It might be time to review your daily care routine.",
            ],
            "Critical": [
                "We have detected potential signs of concern. The redness and size indicate you should see a specialist.",
                "Please pay attention. The automated analysis suggests the wound requires professional assessment.",
            ]
        }
        
        base = random.choice(templates.get(status, templates["Stagnating"]))
        
        if slough > 30:
            base += " We notice some yellow tissue (slough) that might be slowing things down."
        else:
            base += " The wound bed looks mostly clean."
            
        return base

    @staticmethod
    def _generate_doctor_voice(patient_id, metrics, status):
        """Generates a formal SOAP note markdown."""
        import datetime
        date_str = datetime.datetime.now().strftime("%Y-%m-%d")
        
        risk_flag = "LOW RISK"
        if metrics['infection_prob'] > 0.5: risk_flag = "**HIGH INFECTION RISK**"
        
        return f"""
**S.O.A.P. Note Generated by Med-AI Engine**  
**Date:** {date_str} | **Patient ID:** {patient_id}

**Subjective:**  
Patient wound analysis via remote imaging. Automated assessment indicates clinical status: **{status.upper()}**.

**Objective (AI Morphometrics):**  
- **Surface Area:** {metrics['area_cm2']:.2f} cm²
- **Tissue Composition:** {100 - metrics['slough_pct']:.1f}% Granulation, {metrics['slough_pct']:.1f}% Slough/Necrosis
- **Exudate Level:** {'Heavy' if metrics['redness_index'] > 0.6 else 'Moderate'} (Est. from specularity)
- **Erythema Index:** {metrics['redness_index']:.2f} ({risk_flag})

**Assessment:**  
Current healing velocity is {metrics['healing_velocity']:.2f} cm²/week. 
{ 'Wound trajectory is positive.' if metrics['healing_velocity'] > 0 else 'Wound trajectory is stalled/regressing.' }
Probability of colonization/infection is estimated at {metrics['infection_prob']*100:.1f}%.

**Plan:**  
1. Continue current dressing protocol.  
2. {'Review systemic glucose control.' if 'High' in risk_flag else 'Monitor for changes in exudate.'}  
3. Next automated scan scheduled in 24 hours.
"""

    @staticmethod
    def _generate_care_plan(status, slough, risk):
        plans = []
        if slough > 25:
            plans.append("Consider enzymatic debridement or hydrogel to manage slough.")
        if risk > 50:
            plans.append("Monitor temperature and local heat. Consult physician if redness spreads.")
        plans.append("Off-load pressure from the affected area significantly.")
        plans.append("Maintain moisture balance with appropriate dressing.")
        
        return plans
